app:
  title: "KINOSTICK"
  version: 0.0.1

server:
  port: 4000
  hostname: '77.220.143.61'
  servlet:
    context-path: "/api"

streams:
  ports:
    begin: 60000
    end: 60051

tmp:
  dir: /tmp/torrent-stream/

spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
springdoc:
  swagger-ui:
    path: /kinostick/swagger-ui.html